import Footer from "@/components/footer/footer";
import "./globals.css";
import { Inter, Roboto, Poppins } from "next/font/google";
import Navbar from "@/components/navbar/navbar";
import authProvider from "@/components/authProvider/authProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "immeenal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <authProvider>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </authProvider>
      </body>
    </html>
  );
}
